name: Build Exe on Windows

on:
  push:
    branches:
      - master
      - main

jobs:
  build:
    name: Build Exe
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Build exe
      run: |
        pip install pyinstaller
        pyinstaller --onefile --add-binary "C:\hostedtoolcache\windows\Python\3.9.13\x64\Lib\site-packages\tls_client\dependencies\tls-client-64.dll;tls_client/dependencies/" sample.py
    - name: Upload exe
      uses: actions/upload-artifact@v1
      with:
        name: sample_exe
        path: dist/sample.exe
